resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/JassoftLtd/DashVid.io.git
    branch: master

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack_webhook_url}}

jobs:
- name: DashVid.io
  serial_groups: [DashVidDeploy]
  plan:
  - get: source-code
    trigger: true

  - task: Test Deploy
    file: source-code/concourse/build-api.yml
    params:
      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state-tests
      TF_VAR_aws_region: us-east-1
      TF_VAR_environment_name: test-
      TF_VAR_environment_subdomain: test.
      TF_VAR_email_disabled: true
      TF_VAR_token_override: TestToken
      TF_VAR_bucket_force_destroy: true
      TF_VAR_aws_access_key: {{aws_access_key}}
      TF_VAR_aws_secret_key: {{aws_secret_key}}
      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
      TF_VAR_aws_identity_pool: {{aws_identity_pool_test}}
      TF_VAR_dns_zone_id: {{dns_zone_id}}
      TF_VAR_dns_zone_name: {{dns_zone_name}}
      TF_VAR_acm_certificate_arn: {{acm_certificate_arn_test}}
      TF_VAR_api_certificate_arn: {{api_certificate_arn_test}}
      TF_VAR_slack_webhook_url: {{slack_webhook_url}}
      REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_test_ebVZiJokoWIbXD1TNNZ8lj2A
      REACT_APP_AWS_IDENTITY_POOL: {{aws_identity_pool_test}}
      REACT_APP_API_ADRESS: https://test-api.dashvid.io
      AWS_ACCESS_KEY_ID: {{aws_access_key}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}
    on_failure:
      put: slack-alert
      params:
        channel: '#build-notifications'
        text: |
          Test Deploy Failed. Check it out at:
          http://concourse.jassoft.co.uk:8080/builds/$BUILD_ID

  - aggregate:
    - task: API Tests
      file: source-code/concourse/test/api-tests.yml
      params:
        aws_region: us-east-1
        aws_identity_pool: {{aws_identity_pool_test}}
      on_failure:
        put: slack-alert
        params:
          channel: '#build-notifications'
          text: |
            API Tests Failed. Check it out at:
            http://concourse.jassoft.co.uk:8080/builds/$BUILD_ID

    - task: UI Tests
      file: source-code/concourse/test/ui-tests.yml
      on_failure:
        put: slack-alert
        params:
          channel: '#build-notifications'
          text: |
            UI Tests Failed. Check it out at:
            http://concourse.jassoft.co.uk:8080/builds/$BUILD_ID

#  - task: Test Destroy API
#    file: source-code/concourse/destroy-api.yml
#    params:
#      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state-tests
#      TF_VAR_aws_region: us-east-1
#      TF_VAR_environment_name: test-
#      TF_VAR_environment_subdomain: test.
#      TF_VAR_email_disabled: true
#      TF_VAR_token_override: TestToken
#      TF_VAR_bucket_force_destroy: true
#      TF_VAR_aws_access_key: {{aws_access_key}}
#      TF_VAR_aws_secret_key: {{aws_secret_key}}
#      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
#      TF_VAR_aws_identity_pool: {{aws_identity_pool_test}}
#      AWS_ACCESS_KEY_ID: {{aws_access_key}}
#      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}
#
#  - task: Test Destroy UI
#    file: source-code/concourse/destroy-ui.yml
#    params:
#      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state-tests
#      TF_VAR_aws_region: us-east-1
#      TF_VAR_environment_name: test-
#      TF_VAR_environment_subdomain: test.
#      TF_VAR_aws_access_key: {{aws_access_key}}
#      TF_VAR_aws_secret_key: {{aws_secret_key}}
#      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
#      AWS_ACCESS_KEY_ID: {{aws_access_key}}
#      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}

  - task: Production Deploy
    file: source-code/concourse/build-api.yml
    params:
      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state
      TF_VAR_aws_region: eu-west-1
      TF_VAR_aws_access_key: {{aws_access_key}}
      TF_VAR_aws_secret_key: {{aws_secret_key}}
      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
      TF_VAR_aws_identity_pool: {{aws_identity_pool}}
      TF_VAR_dns_zone_id: {{dns_zone_id}}
      TF_VAR_dns_zone_name: {{dns_zone_name}}
      TF_VAR_acm_certificate_arn: {{acm_certificate_arn}}
      TF_VAR_api_certificate_arn: {{api_certificate_arn}}
      TF_VAR_slack_webhook_url: {{slack_webhook_url}}
      REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_live_IYFID6k8KNK8uTVSeKQ6Ync5
      REACT_APP_AWS_IDENTITY_POOL: {{aws_identity_pool}}
      REACT_APP_GA_TRACKING_CODE: {{ga_tracking_code}}
      REACT_APP_API_ADRESS: https://api.dashvid.io
      AWS_ACCESS_KEY_ID: {{aws_access_key}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}
    on_failure:
      put: slack-alert
      params:
        channel: '#build-notifications'
        text: |
          Production Deploy Failed. Check it out at:
          http://concourse.jassoft.co.uk:8080/builds/$BUILD_ID

  - put: slack-alert
    params:
      channel: '#build-notifications'
      text: |
        Production Deployment Successful. Check it out at:
        http://concourse.jassoft.co.uk:8080/builds/$BUILD_ID