resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/jonnyshaw89/VideoServerless.git
    branch: master

jobs:
- name: DashVid.io
  serial_groups: [DashVidDeploy]
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/concourse/build.yml
    params:
      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state-tests
      TF_VAR_aws_region: eu-central-1
      TF_VAR_environment_name: test-
      TF_VAR_aws_account_id: {{aws_account_id}}
      TF_VAR_aws_access_key: {{aws_access_key}}
      TF_VAR_aws_secret_key: {{aws_secret_key}}
      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
      TF_VAR_aws_identity_pool: {{aws_identity_pool}}
  - task: destroy
    file: source-code/concourse/destroy.yml
    params:
      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state-tests
      TF_VAR_aws_region: eu-central-1
      TF_VAR_environment_name: test-
      TF_VAR_aws_account_id: {{aws_account_id}}
      TF_VAR_aws_access_key: {{aws_access_key}}
      TF_VAR_aws_secret_key: {{aws_secret_key}}
      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
      TF_VAR_aws_identity_pool: {{aws_identity_pool}}