resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/JassoftLtd/DashVid.io.git
    branch: master

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack_webhook_url}}

jobs:
- name: DashVid.io
  serial_groups: [DashVidDeploy]
  plan:
  - get: source-code
    trigger: true

  - task: Test Deploy API
    file: source-code/concourse/build-api.yml
    params:
      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state-tests
      TF_VAR_aws_region: us-east-1
      TF_VAR_environment_name: test-
      TF_VAR_environment_subdomain: test.
      TF_VAR_email_disabled: true
      TF_VAR_token_override: TestToken
      TF_VAR_bucket_force_destroy: true
      TF_VAR_aws_access_key: {{aws_access_key}}
      TF_VAR_aws_secret_key: {{aws_secret_key}}
      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
      TF_VAR_aws_identity_pool: {{aws_identity_pool_test}}
      AWS_ACCESS_KEY_ID: {{aws_access_key}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}

  - task: Test Deploy UI
    file: source-code/concourse/build-ui.yml
    params:
      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state-tests
      TF_VAR_aws_region: us-east-1
      TF_VAR_environment_name: test-
      TF_VAR_environment_subdomain: test.
      TF_VAR_dns_zone_id: {{dns_zone_id}}
      TF_VAR_dns_zone_name: {{dns_zone_name}}
      TF_VAR_aws_access_key: {{aws_access_key}}
      TF_VAR_aws_secret_key: {{aws_secret_key}}
      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
      REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_test_ebVZiJokoWIbXD1TNNZ8lj2A
      REACT_APP_AWS_IDENTITY_POOL: {{aws_identity_pool_test}}
      AWS_ACCESS_KEY_ID: {{aws_access_key}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}

  - aggregate:
    - task: API Tests
      file: source-code/concourse/test/api-tests.yml
      params:
        aws_region: us-east-1
        aws_identity_pool: {{aws_identity_pool_test}}
    - task: UI Tests
      file: source-code/concourse/test/ui-tests.yml

#  - task: Test Destroy API
#    file: source-code/concourse/destroy-api.yml
#    params:
#      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state-tests
#      TF_VAR_aws_region: us-east-1
#      TF_VAR_environment_name: test-
#      TF_VAR_environment_subdomain: test.
#      TF_VAR_email_disabled: true
#      TF_VAR_token_override: TestToken
#      TF_VAR_bucket_force_destroy: true
#      TF_VAR_aws_access_key: {{aws_access_key}}
#      TF_VAR_aws_secret_key: {{aws_secret_key}}
#      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
#      TF_VAR_aws_identity_pool: {{aws_identity_pool_test}}
#      AWS_ACCESS_KEY_ID: {{aws_access_key}}
#      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}
#
#  - task: Test Destroy UI
#    file: source-code/concourse/destroy-ui.yml
#    params:
#      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state-tests
#      TF_VAR_aws_region: us-east-1
#      TF_VAR_environment_name: test-
#      TF_VAR_environment_subdomain: test.
#      TF_VAR_aws_access_key: {{aws_access_key}}
#      TF_VAR_aws_secret_key: {{aws_secret_key}}
#      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
#      AWS_ACCESS_KEY_ID: {{aws_access_key}}
#      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}

  - task: Production Deploy API
    file: source-code/concourse/build-api.yml
    params:
      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state
      TF_VAR_aws_region: eu-west-1
      TF_VAR_aws_access_key: {{aws_access_key}}
      TF_VAR_aws_secret_key: {{aws_secret_key}}
      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
      TF_VAR_aws_identity_pool: {{aws_identity_pool}}
      AWS_ACCESS_KEY_ID: {{aws_access_key}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}

  - task: Production Deploy UI
    file: source-code/concourse/build-ui.yml
    params:
      TF_VAR_aws_terraform_state_bucket: dashvid-terraform-state
      TF_VAR_aws_region: eu-west-1
      TF_VAR_aws_access_key: {{aws_access_key}}
      TF_VAR_aws_secret_key: {{aws_secret_key}}
      TF_VAR_stripe_api_key: {{stripe_api_key_test}}
      REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_live_IYFID6k8KNK8uTVSeKQ6Ync5
      REACT_APP_AWS_IDENTITY_POOL: {{aws_identity_pool}}
      AWS_ACCESS_KEY_ID: {{aws_access_key}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_key}}

  - put: slack-alert
    params:
      channel: '#build-notifications'
      text: |
        The build had a result. Check it out at:
        http://concourse.jassoft.co.uk:8080//teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        or at:
        http://concourse.jassoft.co.uk:8080//builds/$BUILD_ID