resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/jonnyshaw89/VideoServerless.git
    branch: master

jobs:
- name: DashVid.io
  plan:
  - get: source-code
    trigger: true
  - task: build
    file: source-code/concourse/build.yml
    params:
      TF_VAR_aws_account_id: 123456789
      TF_VAR_aws_region: eu-west-1