platform: linux

image_resource:
  type: docker-image
  source:
    repository: jonnyshaw89/dashvid-build

inputs:
- name: source-code

params:
  SOME_PARAM: some-default-value

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    cd source-code/terraform
    ./build.sh
    terraform get
    terraform plan