platform: linux

image_resource:
  type: docker-image
  source:
    repository: jonnyshaw89/dashvid-build

inputs:
- name: source-code

run:
  path: sh
  args:
  - -exc
  - |
    cd source-code/terraform
    ./build.sh
    terraform get
    echo $TF_VAR_aws_region
    echo $TF_VAR_aws_terraform_state_bucket
    terraform validate
    terraform apply