platform: linux

image_resource:
  type: docker-image
  source:
    repository: jonnyshaw89/dashvid-build

inputs:
- name: source-code

run:
  path: sh
  args:
  - -exc
  - |
    cd source-code/terraform
    terraform remote config \
        -backend=s3 \
        -backend-config="bucket=$TF_VAR_aws_terraform_state_bucket" \
        -backend-config="key=terraform.tfstate" \
        -backend-config="region=eu-west-1"
    ./build.sh
    terraform get
    echo $TF_VAR_aws_region
    echo $TF_VAR_aws_terraform_state_bucket
    terraform validate
    terraform plan
    ls -ltrh .terraform
    terraform apply
    export DASHVID_UI_ADDRESS=$(terraform output ui-address)
    export DASHVID_API_ADDRESS=$(terraform output api-address)