platform: linux

image_resource:
  type: docker-image
  source:
    repository: jonnyshaw89/dashvid-build

inputs:
- name: source-code

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    ls -ltrh
    ls -ltrh source-code
    ls -ltrh source-code/terraform
    cd source-code/terraform
    source-code/terraform/build.sh