platform: linux

image_resource:
  type: docker-image
  source:
    repository: jonnyshaw89/dashvid-build

inputs:
- name: source-code

run:
  path: sh
  args:
  - -exc
  - |
    whoami
    env
    cd source-code/terraform
    ./build.sh
    echo $aws_account_id
    terraform get
    terraform plan